### ISSUE TITLE
Why not publish the package?

### ISSUE THREAD

**Issue by dnlsilva** [socialcode-rob1/react-native-jitsimeet-custom#14]
Looking at your repo we saw that you didn't publish it on NPM, is there any motivation after that?
My question is why are we going to use it in our project, but because we don't have the package in npm we have to install it directly via git.

**Comment by socialcode-rob1** [comment]
To add the github package registry to your project.

in your project .npmrc, add...

```
//npm.pkg.github.com/:_authToken={PERSONAL_ACCESS_TOKEN}
@socialcode-rob1:registry=https://npm.pkg.github.com
```

PERSONAL_ACCESS_TOKEN needs to be generated, see https://github.com/settings/apps
